# Generated by Django 4.0.6 on 2022-11-15 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0005_profile_featured_communities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
