# Generated by Django 4.0.6 on 2022-11-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0006_alter_gameprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='is_main_gamer_profile',
            field=models.BooleanField(default=False),
        ),
    ]
