# Generated by Django 4.0.6 on 2022-11-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0008_main_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='is_main_gamer_profile',
        ),
    ]
