# Generated by Django 4.0.6 on 2022-11-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0009_remove_gameprofile_is_main_gamer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='game',
            field=models.CharField(choices=[('Valorant', 'Valorant'), ('Call of Duty', 'Call of Duty'), ('League of Legends', 'League of Legends'), ('Counter Strike: GO', 'Counter Strike: GO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='server',
            field=models.CharField(choices=[('Val', [('APAC', 'Asia Pacific'), ('EMEA', 'Europe'), ('NA', 'North America'), ('JA', 'Japan')]), ('COD', [('APAC', 'Asia Pacific'), ('EMEA', 'Europe'), ('NA', 'North America')]), ('LOL', [('APAC', 'Asia Pacific'), ('EMEA', 'Europe'), ('NA', 'North America')]), ('CS', [('EMEA', 'Europe'), ('NA', 'North America')])], max_length=50),
        ),
    ]
