# Generated by Django 4.0.6 on 2022-11-29 04:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0010_alter_gameprofile_game_alter_gameprofile_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='additional_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=500, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
