# Generated by Django 4.0.6 on 2022-11-30 02:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0011_gameprofile_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='additional_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=500, null=True), blank=True, default=list, null=True, size=None), blank=True, default=list, null=True, size=None),
        ),
    ]
