# Generated by Django 4.0.6 on 2022-12-02 03:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0013_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=500, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
