# Generated by Django 4.0.6 on 2022-12-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0014_community_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
