# Generated by Django 4.0.6 on 2022-12-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0015_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='achievements',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='communication_level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='free_time_slots',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='looking_for_friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='remarks',
            field=models.CharField(blank='', default='', max_length=400),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='years_of_exp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
