# Generated by Django 4.0.6 on 2022-12-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0016_gameprofile_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='free_time_slots',
            field=models.TimeField(default=None, null=True),
        ),
    ]
