# Generated by Django 4.0.6 on 2022-12-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0017_alter_gameprofile_free_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='remarks',
            field=models.CharField(blank='', default='', max_length=400, null=True),
        ),
    ]
