# Generated by Django 4.0.6 on 2022-12-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0018_alter_gameprofile_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
