# Generated by Django 4.0.6 on 2022-12-12 03:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0019_alter_gameprofile_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameprofile',
            old_name='free_time_slots',
            new_name='free_time_slots_end_time',
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='free_time_slots_start_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='time_slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(default=None, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
