# Generated by Django 4.0.6 on 2022-12-12 05:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0020_rename_free_time_slots_gameprofile_free_time_slots_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='roles_rating',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
