# Generated by Django 4.0.6 on 2022-12-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0021_gameprofile_roles_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='free_time_slots_end_time',
        ),
        migrations.RemoveField(
            model_name='gameprofile',
            name='free_time_slots_start_time',
        ),
        migrations.RemoveField(
            model_name='gameprofile',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='time_available',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
