# Generated by Django 4.0.6 on 2022-12-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0023_alter_gameprofile_communication_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='in_game_user_id',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
