# Generated by Django 4.0.6 on 2022-12-15 03:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0024_gameprofile_in_game_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
