# Generated by Django 4.0.6 on 2022-12-15 04:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0025_gameprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), blank=True, default=list, null=True, size=None), blank=True, default=list, null=True, size=None),
        ),
    ]
