# Generated by Django 4.0.6 on 2022-12-17 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0026_alter_gameprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_lft_lfp_post',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vouches',
            field=models.ManyToManyField(blank=True, default=None, related_name='vouches', to=settings.AUTH_USER_MODEL),
        ),
    ]
