# Generated by Django 4.0.6 on 2022-12-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0027_post_is_lft_lfp_post_post_vouches'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vouch_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
