# Generated by Django 4.0.6 on 2022-10-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0049_community_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='created_by',
        ),
    ]
