# Generated by Django 4.0.6 on 2022-10-15 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0051_community_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='posts',
            field=models.ManyToManyField(blank=True, default=None, related_name='community_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
