# Generated by Django 4.0.6 on 2022-10-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0053_remove_community_posts_remove_post_community_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='page3.community'),
        ),
    ]
