# Generated by Django 4.0.6 on 2022-11-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0054_remove_community_post_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='communities',
            field=models.ManyToManyField(blank=True, default=None, related_name='followers', to='page3.community'),
        ),
    ]
