# Generated by Django 4.0.6 on 2022-11-10 02:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0055_profile_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images_ids_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1, null=True), blank=True, null=True, size=None),
        ),
    ]
