# Generated by Django 4.0.6 on 2022-11-10 02:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0057_alter_post_images_ids_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images_ids_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
