# Generated by Django 4.0.6 on 2022-11-10 02:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0058_alter_post_images_ids_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images_urls_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=500, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
